### ISSUE TITLE
[event_settings] исправить работу блока

### ISSUE THREAD

**Issue by tixUA** [nicolaypetrovich/rocket-nationsorg#30]
При нажатии на поле, будет выбор фото из файлов на компьютере
http://prntscr.com/k39xiq

**Comment by tixUA** [comment]
в ie11 иконка фотика вообще не работает

**Comment by tixUA** [comment]
в IE все так же

**Comment by tixUA** [comment]
фывфы

**Comment by SynytcaEvgen** [comment]
Нужно еще раз затестить на IE должно работь

**Comment by tixUA** [comment]
На IE11 все так же, когда нажимаешь по иконке
