### ISSUE TITLE
[forum] Нет поиска 

### ISSUE THREAD

**Issue by tixUA** [nicolaypetrovich/rocket-nationsorg#36]
http://prntscr.com/k3cimf

**Comment by tixUA** [comment]
http://prntscr.com/k9wjfo
поле поиска и кнопка слипаются, поиск увеличивается по высоте, на 375 и меньше, кнопку можно опустить под поиск или сделать иконкой поиска
320-574

**Comment by SynytcaEvgen** [comment]
Был глюк с адаптацией
